#!/bin/bash

make_certs(){
    echo "1:3) Generate private key..."
    openssl genrsa -out private-key.pem 4096

    echo "2:3) Generate signing request..."
    openssl req -new -key private-key.pem -out certificate-signing-request.pem

    echo "3:3) Self sign the request (or use a 3rd party crook, i.e verisign)..."
    # We are creating a self-signed cert, using our private key.
    openssl x509 -req -in certificate-signing-request.pem -signkey private-key.pem -out certificate.pem
    echo ""

    # if you see "unable to write 'random state'"
    # http://stackoverflow.com/a/94458/125083
    echo "done!"
}

echo "Generating keys and certs for server..."
cd server
echo ""
make_certs

cd ..

echo "Generating keys and certs for client..."
cd client
echo ""
make_certs
